const router=require('express').Router();
const task=require('../controllers/taskController');
const page=require('../controllers/pageController');
const projectRepo=require('../repositories/projectRepository');
const goalRepo=require('../repositories/goalRepository');
const habitRepo=require('../repositories/habitRepository');
const noteRepo=require('../repositories/noteRepository');
const milestoneRepo=require('../repositories/milestoneRepository');
const notifications=require('../services/notificationService');
const {requireApiAuth}=require('../middleware/auth');
router.use(requireApiAuth);
router.get('/tasks',task.list);
router.post('/tasks/parse',task.parse);
router.get('/tasks/:id',task.get);
router.post('/tasks',task.create);
router.put('/tasks/:id',task.update);
router.patch('/tasks/:id',task.update);
router.post('/tasks/:id/complete',task.complete);
router.post('/tasks/:id/duplicate',task.duplicate);
router.post('/tasks/:id/snooze',task.snooze);
router.post('/tasks/:id/reschedule',task.reschedule);
router.post('/tasks/:id/subtasks',task.subtask);
router.delete('/tasks/:id',task.remove);
router.get('/analytics',page.apiAnalytics);
router.get('/notifications',async(req,res,next)=>{try{await notifications.syncForOwner(req.session.user.id);const items=await notifications.list(req.session.user.id,{unreadOnly:false});res.json({items,unread:items.filter(item=>!item.read).length})}catch(e){next(e)}});
router.post('/notifications/:id/read',async(req,res,next)=>{try{const item=await notifications.markRead(req.session.user.id,req.params.id);if(!item)return res.status(404).json({error:'Notification not found'});res.json({notification:item})}catch(e){next(e)}});
router.post('/notifications/read-all',async(req,res,next)=>{try{res.json(await notifications.markAllRead(req.session.user.id))}catch(e){next(e)}});
router.post('/notifications/sync',async(req,res,next)=>{try{res.json(await notifications.syncForOwner(req.session.user.id))}catch(e){next(e)}});
router.get('/milestones',async(req,res,next)=>{try{res.json({items:await milestoneRepo.list(req.session.user.id,{project:req.query.project,goal:req.query.goal})})}catch(e){next(e)}});
router.post('/milestones',async(req,res,next)=>{try{if(!String(req.body.title||'').trim())return res.status(422).json({error:'Milestone title is required'});const item=await milestoneRepo.create(req.session.user.id,{title:String(req.body.title).trim(),dueDate:req.body.dueDate||undefined,project:req.body.project||undefined,goal:req.body.goal||undefined,status:'todo',progress:0});res.status(201).json({milestone:item})}catch(e){next(e)}});
router.patch('/milestones/:id',async(req,res,next)=>{try{const item=await milestoneRepo.update(req.session.user.id,req.params.id,{status:req.body.status,progress:Math.max(0,Math.min(100,Number(req.body.progress||0)))});if(!item)return res.status(404).json({error:'Milestone not found'});res.json({milestone:item})}catch(e){next(e)}});
router.get('/projects',async(req,res,next)=>{try{res.json({items:await projectRepo.list(req.session.user.id)})}catch(e){next(e)}});
router.post('/projects',async(req,res,next)=>{try{const p=await projectRepo.create(req.session.user.id,{name:req.body.name,description:req.body.description,color:req.body.color||'#526dff',deadline:req.body.deadline,status:'active'});res.status(201).json({project:p})}catch(e){next(e)}});
router.get('/goals',async(req,res,next)=>{try{res.json({items:await goalRepo.list(req.session.user.id)})}catch(e){next(e)}});
router.post('/goals',async(req,res,next)=>{try{const g=await goalRepo.create(req.session.user.id,{title:req.body.title,description:req.body.description,category:req.body.category||'Career',targetDate:req.body.targetDate,priority:req.body.priority||'high'});res.status(201).json({goal:g})}catch(e){next(e)}});
router.post('/habits',async(req,res,next)=>{try{const h=await habitRepo.create(req.session.user.id,{name:req.body.name,description:req.body.description,color:req.body.color||'#21b88a',frequency:{type:req.body.frequency||'daily',days:[]}});res.status(201).json({habit:h})}catch(e){next(e)}});
router.post('/habits/:id/log',async(req,res,next)=>{try{const h=await habitRepo.log(req.session.user.id,req.params.id,new Date());res.json({habitLog:h})}catch(e){next(e)}});
router.post('/notes',async(req,res,next)=>{try{const n=await noteRepo.create(req.session.user.id,{title:req.body.title,content:req.body.content,tags:String(req.body.tags||'').split(',').map(x=>x.trim()).filter(Boolean)});res.status(201).json({note:n})}catch(e){next(e)}});
module.exports=router;
