const taskService=require('../services/taskService');const analytics=require('../services/analyticsService');const projects=require('../repositories/projectRepository');const goals=require('../repositories/goalRepository');const habits=require('../repositories/habitRepository');const notes=require('../repositories/noteRepository');const activity=require('../services/activityService');const notifications=require('../services/notificationService');const milestones=require('../repositories/milestoneRepository');
async function dashboard(req,res,next){try{const owner=req.session.user.id;const [summary,analyticsData,projectItems,goalItems,habitItems,activityItems,notificationItems]=await Promise.all([taskService.summary(owner),analytics.getAnalytics(owner),projects.list(owner),goals.list(owner),habits.list(owner),activity.recent(owner),notifications.list(owner)]);const enrichedProjects=await Promise.all(projectItems.map(async p=>{const ts=await taskService.list(owner,{project:String(p._id)});return {...p,taskCount:ts.length,completedCount:ts.filter(t=>t.status==='completed').length,progress:ts.length?Math.round(ts.filter(t=>t.status==='completed').length/ts.length*100):0}}));res.render('dashboard',{pageTitle:'Dashboard',active:'dashboard',summary,analyticsData,projects:enrichedProjects,goals:goalItems.filter(g=>g.status==='active').slice(0,4),habits:analyticsData.habits.items,activities:activityItems,notifications:notificationItems})}catch(e){next(e)}}
async function tasksPage(req,res,next){try{const owner=req.session.user.id;res.render('tasks',{pageTitle:'Tasks',active:'tasks',tasks:await taskService.list(owner,{}),projects:await projects.list(owner),goals:await goals.list(owner)})}catch(e){next(e)}}
async function goalsPage(req,res,next){try{res.render('goals',{pageTitle:'Goals',active:'goals',goals:await goals.list(req.session.user.id)})}catch(e){next(e)}}
async function projectsPage(req,res,next){try{res.render('projects',{pageTitle:'Projects',active:'projects',projects:await projects.list(req.session.user.id)})}catch(e){next(e)}}
async function milestonesPage(req,res,next){try{const owner=req.session.user.id;const items=await milestones.list(owner);const allTasks=await taskService.list(owner,{});const enriched=items.map(item=>{const linked=allTasks.filter(task=>String(task.parentTask)===String(item._id)||String(task.milestone)===String(item._id));const completed=linked.filter(task=>task.status==='completed').length;return {...item,taskCount:linked.length,completedCount:completed,calculatedProgress:linked.length?Math.round(completed/linked.length*100):Number(item.progress||0)}});res.render('milestones',{pageTitle:'Milestones',active:'milestones',milestones:enriched,projects:await projects.list(owner),goals:await goals.list(owner)})}catch(e){next(e)}}
async function habitsPage(req,res,next){try{const hs=await habits.list(req.session.user.id);const stats=await analytics.habitStats(req.session.user.id,hs);res.render('habits',{pageTitle:'Habits',active:'habits',habits:stats.items})}catch(e){next(e)}}
async function notesPage(req,res,next){try{res.render('notes',{pageTitle:'Notes',active:'notes',notes:await notes.list(req.session.user.id)})}catch(e){next(e)}}
async function calendarPage(req,res,next){try{const now=new Date(),year=Number(req.query.year||now.getFullYear()),month=Number(req.query.month??now.getMonth());const first=new Date(year,month,1),daysInMonth=new Date(year,month+1,0).getDate(),leading=first.getDay();const all=await taskService.list(req.session.user.id,{});const days=[];for(let i=0;i<leading;i++)days.push(null);for(let day=1;day<=daysInMonth;day++){const date=new Date(year,month,day);days.push({day,date,tasks:all.filter(t=>t.dueDate&&new Date(t.dueDate).toDateString()===date.toDateString())})}res.render('calendar',{pageTitle:'Calendar',active:'calendar',days,year,month,label:first.toLocaleString('en-IN',{month:'long',year:'numeric'})})}catch(e){next(e)}}
async function analyticsPage(req,res,next){try{res.render('analytics',{pageTitle:'Analytics',active:'analytics'})}catch(e){next(e)}}
async function searchPage(req,res,next){try{const q=String(req.query.q||'').trim().toLowerCase();const owner=req.session.user.id;if(!q)return res.render('search',{pageTitle:'Search workspace',active:'search',q,results:{tasks:[],projects:[],goals:[],habits:[],notes:[]}});const [taskItems,projectItems,goalItems,habitItems,noteItems]=await Promise.all([taskService.list(owner,{search:q}),projects.list(owner),goals.list(owner),habits.list(owner),notes.list(owner)]);const includes=(...values)=>values.some(v=>String(v||'').toLowerCase().includes(q));res.render('search',{pageTitle:'Search workspace',active:'search',q,results:{tasks:taskItems,projects:projectItems.filter(x=>includes(x.name,x.description)),goals:goalItems.filter(x=>includes(x.title,x.description,x.category)),habits:habitItems.filter(x=>includes(x.name,x.description)),notes:noteItems.filter(x=>includes(x.title,x.content,(x.tags||[]).join(' ')))}})}catch(e){next(e)}}
function settingsPage(req,res){res.render('settings',{pageTitle:'Settings',active:'settings'})}
async function apiAnalytics(req,res,next){try{res.json(await analytics.getAnalytics(req.session.user.id))}catch(e){next(e)}}
module.exports={dashboard,tasksPage,goalsPage,projectsPage,milestonesPage,habitsPage,notesPage,calendarPage,analyticsPage,searchPage,settingsPage,apiAnalytics};
