const path=require('node:path');
const express=require('express');
const session=require('express-session');
const MongoStore=require('connect-mongo');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const mongoSanitize=require('express-mongo-sanitize');
const morgan=require('morgan');
const env=require('./config/env');
const {attachUser}=require('./middleware/auth');
const {issue,verify}=require('./middleware/csrf');
const {notFound,errorHandler}=require('./middleware/errorHandler');

const app=express();
if(env.isProduction)app.set('trust proxy',1);
app.set('view engine','ejs');
app.set('views',path.join(__dirname,'../views'));
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:false}));
app.use(morgan('dev'));
app.use(express.urlencoded({extended:true}));
app.use(express.json({limit:'100kb'}));
app.use(mongoSanitize());
app.use(rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:true,legacyHeaders:false}));
const sessionOptions={secret:env.sessionSecret,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:env.isProduction,maxAge:1000*60*60*24*14}};
if(env.mongoUri&&process.env.MONGO_SESSION==='true')sessionOptions.store=MongoStore.create({mongoUrl:env.mongoUri,collectionName:'sessions'});
app.use(session(sessionOptions));
app.use(attachUser);
app.use(issue);
app.use(verify);
app.use(express.static(path.join(__dirname,'../public')));
app.use(require('./routes/authRoutes'));
app.use(require('./routes/pageRoutes'));
app.use('/api',require('./routes/apiRoutes'));
app.use(notFound);
app.use(errorHandler);
module.exports=app;
